package:
  name: perses-dev
  version: !!str 0.0.0

source:
  path: ../../

build:
  preserve_egg_dir: True
  number: 0

requirements:
  build:
    - python
    - setuptools
    - numpy
    - scipy
    - numexpr
    - autograd
    - pymbar
    - openmm >=7.1.0
    - parmed
    - openmoltools
    - alchemy >=1.2.3
    - openmmtools
    - numba
    - netcdf4
    - matplotlib
    - seaborn
    - pdbfixer
    - mdtraj
    - parmed # for testing/debugging
    - pdbfixer
    - lxml
    - networkx >=2.0

  run:
    - python
    - setuptools
    - numpy
    - scipy
    - numexpr
    - autograd
    - pymbar
    - openmm >=7.1.0
    - parmed
    - openmoltools
    - alchemy >=1.2.3
    - openmmtools
    - numba
    - netcdf4
    - matplotlib
    - seaborn
    - pdbfixer
    - mdtraj
    - parmed # for testing/debugging
    - pdbfixer
    - lxml
    - networkx >=2.0

test:
  requires:
    - nose
    - nose-timer
  imports:
    - perses

about:
  home: https://github.com/choderalab/perses
  license: GNU Lesser General Public License v2 or later (LGPLv2+)
