package:
  name: perses-dev
  version: !!str 0.0.0

source:
  path: ../../

build:
  preserve_egg_dir: True
  number: 0

requirements:
  build:
    - python
    - setuptools
    - numpy
    - scipy
    - numexpr
    - autograd
    - pymbar
    - cuda92
    - openmm >=7.3.0
    - parmed
    - openmoltools
    - openmmtools
    - numba
    - netcdf4
    - matplotlib
    - seaborn
    - mdtraj
    - parmed
    - pdbfixer
    - lxml
    - networkx >=2.0
    - yank

  run:
    - python
    - setuptools
    - numpy
    - scipy
    - numexpr
    - autograd
    - pymbar
    - cuda92
    - openmm >=7.3.0
    - parmed
    - openmoltools
    - openmmtools
    - numba
    - netcdf4
    - matplotlib
    - seaborn
    - mdtraj
    - parmed
    - pdbfixer
    - lxml
    - networkx >=2.0
    - openeye-toolkits
    - dask
    - distributed
    - progressbar2
    - yank

test:
  requires:
    - nose
    - nose-timer
  imports:
    - perses

about:
  home: https://github.com/choderalab/perses
  license: GNU Lesser General Public License v2 or later (LGPLv2+)
